name = "notifytg"
main = "src/index.js"
compatibility_date = "2023-05-12"
[ vars ]
TOKEN = ""
send_email = [
    {type = "send_email", name = "SEB"},
]
CFURL = "https://example.example.workers.dev/"

[[ d1_databases ]]
binding = "DB"
database_name = "emaildb"
database_id = ""
